<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SHIP42478287SU05</name>
   <tag></tag>
   <elementGuidId>4b9b9403-a98f-455d-a0cf-c1a4ca040aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ShipmentDetails_headerTextStyle__2oces</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[3]/div[3]/div/div/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e536d41e-4c29-4fa4-ae36-3319569729e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ShipmentDetails_headerTextStyle__2oces</value>
      <webElementGuid>57782447-83c7-467c-84a7-d5ce5f552c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SHIP42478287SU05</value>
      <webElementGuid>a8ceac60-0d93-49a3-bc5e-4ce902717a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;application 
       
      false&quot;]/div[@class=&quot;mbe-micro-ui&quot;]/div[1]/div[@class=&quot;mbe_micro_ui&quot;]/div[@class=&quot;ShipmentDetails_root__C50D_&quot;]/div[1]/span[@class=&quot;ShipmentDetails_headerTextStyle__2oces&quot;]</value>
      <webElementGuid>be9a3b3f-3d80-4d43-8aa7-c217cdfa4340</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[3]/div[3]/div/div/div/div/div/span</value>
      <webElementGuid>8eefe25f-9b0a-4fd3-9cf5-ff2669086388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipments >'])[1]/following::span[1]</value>
      <webElementGuid>3c814674-dd64-424a-956b-5a748140ac15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHIP8732784KS'])[1]/following::span[3]</value>
      <webElementGuid>22834b69-e3b8-446a-bea1-04beb58c5a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tendered'])[2]/preceding::span[2]</value>
      <webElementGuid>549ca035-33fb-4eb4-941e-c997bf6779ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div/div/div/span</value>
      <webElementGuid>950f6b18-4686-49c8-83d2-e1ab95c9b2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SHIP42478287SU05' or . = 'SHIP42478287SU05')]</value>
      <webElementGuid>a3465756-2ff8-456f-b2ea-77a9a1942850</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
