<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_shipmentNumber</name>
   <tag></tag>
   <elementGuidId>3fdc4158-e39e-42b2-8445-31b6a4e606cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@class,'application') and not(contains(@class,'not-currently-active'))]//tr)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d52aa9c3-70be-4d33-bc2d-fd9fd323dd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5ff45ad1-ee89-4caa-92e1-21287211bceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-focus-view-landing </value>
      <webElementGuid>38b1c436-42a0-45ca-bfb9-008f2c200af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>1e21fddf-0f23-4d75-96a7-3341193ade2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>0dee578a-4f4f-4ae8-a4ca-3eb5ccb61d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>59267ded-ffa5-43c6-b050-0cfdac506fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-grid-col-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>746f370e-345b-43fa-abe1-284b23dc451f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SHIP42478287SU05</value>
      <webElementGuid>c0973f20-2110-45e1-b083-92dc0131b7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blume-grid-w&quot;)/div[@class=&quot;wrapper-table&quot;]/div[@class=&quot;k-widget k-grid DataGrid hasCheckBoxColumn hasHeader&quot;]/div[@class=&quot;k-grid-container&quot;]/div[@class=&quot;k-grid-content k-virtual-content&quot;]/div[1]/table[@class=&quot;k-grid-table&quot;]/tbody[1]/tr[@class=&quot;k-master-row&quot;]/td[@class=&quot;tab-focus-view-landing&quot;]</value>
      <webElementGuid>93666bf9-81c6-4b20-a3a0-80d709008d88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='blume-grid-w']/div[2]/div/div[2]/div/div/table/tbody/tr/td[3]</value>
      <webElementGuid>38870aaa-0b8b-4d01-8a50-5352d667f823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Reference #'])[1]/following::td[3]</value>
      <webElementGuid>0ce39585-1d79-4670-b757-7b92f5e864c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Term'])[1]/following::td[3]</value>
      <webElementGuid>9cdffa3a-0ff6-4de6-bed5-dedbef630271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DRAY'])[1]/preceding::td[1]</value>
      <webElementGuid>98bb2eb7-29ce-4507-a78e-dc6d2fa07f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tendered'])[1]/preceding::td[2]</value>
      <webElementGuid>08672ead-4d09-4496-a128-06476eb51d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SHIP42478287SU05']/parent::*</value>
      <webElementGuid>d7e05f63-524b-41cc-88c9-b831b987d1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>b58aa178-2ae4-4879-8845-e120b484d513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'SHIP42478287SU05' or . = 'SHIP42478287SU05')]</value>
      <webElementGuid>0b32685a-214f-48ea-9d54-d0fa7ac9b8b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
