<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipment_k-textbox kendoSearchBox</name>
   <tag></tag>
   <elementGuidId>0a9f7efd-5fe7-4418-b9d8-9c3a5eb4f9a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.k-textbox.kendoSearchBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc06eed3-39a8-406a-b981-b0f8826dd2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-textbox kendoSearchBox</value>
      <webElementGuid>3af1d83c-aa62-46f0-9de6-015858a3b1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>0b68955d-3a85-4e4d-bde7-e973ab6ff3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blume-grid-w&quot;)/div[@class=&quot;action-container&quot;]/div[@class=&quot;flex-center row1&quot;]/div[@class=&quot;gridSearchContainer&quot;]/div[@class=&quot;kendo-search-box-container kendo-search-box-container-active&quot;]/input[@class=&quot;k-textbox kendoSearchBox&quot;]</value>
      <webElementGuid>d291c4b4-7b6b-44b2-96c3-99b515e47638</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>b2bf6e65-bde4-4502-a810-2fe5ad19cc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='blume-grid-w']/div/div[2]/div/div/input</value>
      <webElementGuid>dc15d42f-55d2-47ec-b8ca-3556180fea97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>b2ffe8a9-a3ac-4739-a904-03e27f2d448e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search...']</value>
      <webElementGuid>d8c06b4c-cbb5-4a52-9044-40e49d44b163</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
