<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_SHIP42478287SU10</name>
   <tag></tag>
   <elementGuidId>f39cdd1f-0718-4340-ab20-0f162278c8d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='blume-grid-w']/div[2]/div/div[2]/div/div/table/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3a6e95f0-32ba-442c-a2db-2cffcaf1cd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>87227a6d-4a4c-419d-b315-03a62206b792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-focus-view-landing </value>
      <webElementGuid>793ac438-0a02-4751-8415-4da6fe315e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>20c2aeef-a4c6-4390-af37-d7067532ad59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>605d058b-a903-425c-b0e6-c316bc917485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fdb1d177-8c81-4eca-844f-233a028248cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-grid-col-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>58bb79f1-5cbc-41b0-bd0d-e7bb2fcca6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SHIP42478287SU10</value>
      <webElementGuid>70856d6f-dffa-4b81-ba69-997680bfb7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blume-grid-w&quot;)/div[@class=&quot;wrapper-table&quot;]/div[@class=&quot;k-widget k-grid DataGrid hasCheckBoxColumn hasHeader&quot;]/div[@class=&quot;k-grid-container&quot;]/div[@class=&quot;k-grid-content k-virtual-content&quot;]/div[1]/table[@class=&quot;k-grid-table&quot;]/tbody[1]/tr[@class=&quot;k-master-row&quot;]/td[@class=&quot;tab-focus-view-landing&quot;]</value>
      <webElementGuid>b9a9771f-644b-4f89-be7c-74e819ed0bfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='blume-grid-w']/div[2]/div/div[2]/div/div/table/tbody/tr/td[3]</value>
      <webElementGuid>bc9b8f27-c9ee-4a65-9241-fb753f99b5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Reference #'])[1]/following::td[3]</value>
      <webElementGuid>d832180e-0294-4d0b-917c-2adfe3118609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Term'])[1]/following::td[3]</value>
      <webElementGuid>27906fed-77bc-4e7b-8c81-55a4d6eaf486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DRAY'])[1]/preceding::td[1]</value>
      <webElementGuid>ca9c8fa0-5147-443a-aab1-804fc2cf2cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assigned'])[1]/preceding::td[2]</value>
      <webElementGuid>4bba82d2-2604-4e32-892a-57d6f37a744e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SHIP42478287SU10']/parent::*</value>
      <webElementGuid>ed25f8d6-9cdb-4c55-b914-0edc7d4a6ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>4441b445-b5c7-4441-8113-20ee4b3eec40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'SHIP42478287SU10' or . = 'SHIP42478287SU10')]</value>
      <webElementGuid>9f892298-afc5-42ee-9a80-8f95df1c46fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
